### ISSUE TITLE
leak: lot of mongo databases are created and not deleted

### ISSUE THREAD

**Issue by zvictor** [arunoda/laika#14]
I observed that when running Laika, a lot of mongo databases are created and not deleted.
I have to run the following code at shell every some while:

``` javascript
$ mongo
> var dbs = db.getMongo().getDBNames()
for(var i in dbs){
    db = db.getMongo().getDB( dbs[i] );
    if(db.getName() == "test" || db.getName() == "admin" || db.getName() == "local")
        continue;

    print( "dropping db " + db.getName() );
    db.dropDatabase();
}
```

Note: I am not using the _options that makes testing much speeder_ recommended on docs.

**Comment by arunoda** [comment]
Yes. this is really an issue I discovered from the day one.
But actually I could find a solution.

`Laika` drops the the db after the test has been ended.
However everytime there is a single db stayed without deleting itself.
I could find a way yet, to figure out the cause.

related: #6 

This is pretty big issue. I still trying to find out the problem.
In the meantime, only solution is to delete these leaked dbs manually.

> What I do is load mongodb with a separate data-directory which I delete time to time

### About the speeder options.

My drive is 5400 RPM one. So that makes my tests faster. But if you are using a SSD I think, it does not make much sense. (BTW, those options reduce the disk space)

**Comment by arunoda** [comment]
I think rather than figuring out the problem (much harder), we could prefix dbs with `laika-`. And before running any test, we can simply delete databases already leaking.

need to figure out, weather it took more time to start the testing? but it won't be a problem.

**Comment by arunoda** [comment]
BTW: I found the cause for this. Added a fix. see: 257885d1a3d361d48b777244c39f4178e932722a

@zvictor I updated the npm, can you verify the fix. I can then release 0.2. This cause me to stay in 0.1

**Comment by arunoda** [comment]
Above fix introduced some other nasty leaking issue. Now both are fixed here 0c30007cb1fae1c4e904eb325dc84439ea5f18c6 & 6e459e2345d6aef6332d3a8cb1a56d7fbdf83c2d

`published to npm with 0.1.25`

**Comment by zvictor** [comment]
I have tried now, and it seems to be working smoothly! thanks!

**Comment by zvictor** [comment]
actually, it is not okay...
laika is freezing in **cleaning up injected code** message, and the databases are not being deleted.

these are my databases now:

```
_laika  7   192.1 MB    
admin   0   n/a 
laika-49ysQdzi5m    7   192.1 MB    
laika-BxNTSI3PTp    7   192.1 MB    
laika-cvYlUvHUfB    7   192.1 MB    
laika-hygWP24sA8    7   192.1 MB    
laika-L08IbRX80D    7   192.1 MB    
laika-mvpX1bF75k    7   192.1 MB    
laika-OA1KM4HYQ9    7   192.1 MB    
laika-OGQS5kWvkj    7   192.1 MB    
laika-qPbNNx6nyw    7   192.1 MB    
laika-rijWMUXih5    7   192.1 MB    
laika-s0unZcZ7yM    7   192.1 MB    
laika-uO93BtWtQn    7   192.1 MB    
laika-WqpHdpcfOE    0   n/a 
laika-Xt9dhTmWDf    7   192.1 MB
local   1   64 MB
```

**Comment by arunoda** [comment]
Now we do start laika tests with cleaning up the laika dbs first. It only tooks ~50 ms. So nothing to worry about.
Please reopen if the leak exists in the latest version of laika.
