### ISSUE TITLE
Cannot file module .meteor/release/METEOR@0.9.1.release.json

### ISSUE THREAD

**Issue by ido-ran** [arunoda/laika#140]
I'm following this [this tutorial](http://mherman.org/blog/2014/01/29/meteor-dot-js-in-action-create-an-app-test-with-laika/#.VAmrrmSSzKg) and when I try to run Laika test I get the output bellow.

I'm new to meteor and Laika so I might configure something wrong.

```
  injecting laika...
  loading phantomjs...
  loading initial app pool...
  cleaning up injected code


module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/me/.meteor/releases/METEOR@0.9.1.release.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.getMeteorToolsPath (/usr/local/lib/node_modules/laika/lib/helpers.js:33:18)
    at Object.getMeteorNode (/usr/local/lib/node_modules/laika/lib/helpers.js:43:35)
    at Object.getMeteoriteNode (/usr/local/lib/node_modules/laika/lib/helpers.js:59:20)
    at detectConfig (/usr/local/lib/node_modules/laika/lib/app_pool.js:83:35)
    at new AppPool (/usr/local/lib/node_modules/laika/lib/app_pool.js:16:19)
    at /usr/local/lib/node_modules/laika/bin/_laika:90:17
```

**Comment by jasperkennis** [comment]
Got the same problem. It's because it's looking in the wrong folder I guess, but I can't figure out how to use the `path filter` argument.

**Comment by dfucci** [comment]
Got the same with meteor v 0.9.1.1 and Laika 0.3.9

**Comment by lacco** [comment]
Looks like a change in Meteor >= 0.9.0 doesn't generate the expected file anymore for current Meteor version. I am on Meteor 0.9.2 and get `Cannot find module '/Users/xxx/.meteor/releases/METEOR@0.9.2.1.release.json'`.

I have the following files:

``` bash
> ls ~/.meteor/releases/
0.8.3.notices.json
0.8.3.release.json
0.9.1.1.release.json
latest -> 0.9.1.1.release.json
```

**Comment by jwjames** [comment]
+1 I also have this problem.

**Comment by jwjames** [comment]
I uninstalled and reinstalled meteor and it appears that there is no releases file for 0.9.2.

**Comment by apendua** [comment]
@ido-ran @jwjames Please try out my branch. This should already work now.

**Comment by dfucci** [comment]
upgraded today to 0.9.3 and tried @apendua branch  
Now laika gets stuck at _loading phantomjs_

**Comment by apendua** [comment]
@dfucci Are you sure the development bundle is not being downloaded in the background?

**Comment by apendua** [comment]
@dfucci I have tried it locally and it works just fine with `0.9.3`. If you're expecting problems they might be cause by something else, like updating packages or something.

**Comment by dfucci** [comment]
@apendua do you mean the XCode Command Line Tools? These are already installed.  
Just tried on an freshly created meteor project and still got   

```
Cannot find module '/Users/dfucci/.meteor/releases/METEOR@0.9.3.release.json'
```

**Comment by apendua** [comment]
@dfucci If laika is trying to look for that file it means you're not using the latest version. I can see that @arunoda has already published a new version to the npm repository, so you may want to update your installation.
