### ISSUE TITLE
Can't run Hello World sample on Nitrous with Meteor 0.9.2.2

### ISSUE THREAD

**Issue by ghost** [arunoda/laika#142]
I am trying to get setup to do testing with Meteor. I use Nitrous.io for my development - not sure if that has any correlation to this or not.

Meteor is installed and reports v0.9.9.2
PhantomJS is installed reports v1.9.7
Mocha is installed and reports 1.21.4
Laika is installed and reports v0.3.9

I can run the app in meteor normally with no errors.
When I try to run laika, it just hangs after "loading phantomjs..."

If I run laika -V, it shows:
[app touch log] => Started proxy.  
[app touch log] I20140918-08:51:18.902(0)? laika code injected and listening on: 15528  
[app touch log] => Started your app.  
[app touch log]  
=> App running at: http://chrisb.dev.arsnebula.com

but no tests are run, and it just sits there.

Any help would be appreciated getting this running.

**Comment by apendua** [comment]
@chrismbeckett Can you try updating laika to `0.3.10`?

**Comment by ghost** [comment]
I have similar issue on Meteor 0.9.3 and Laika 0.3.10, tried with a clean app. @chrismbeckett did you solve this?

**Comment by ghost** [comment]
I am doing all my testing with CasperJS and Mocha-CasperJS now. It's just easier, and it works. It's functional testing, not real unit testing, but I can build test harnesses and write tests to exercise specific code paths so in the end I get the pass or fail on the things I care about.

**Comment by ghost** [comment]
Thanks @chrismbeckett, looks nice too, I'll try it. But also want to try laika, I like the stable thing in mup, and i'm sure that laika has the same. @chrismbeckett do you know what it can be?
