### ISSUE TITLE
test using client and server always gives timeout

### ISSUE THREAD

**Issue by hoolymama** [arunoda/laika#15]
I'm just trying to run the test: 'using both client and the server' as per the demo

```
test('using both client and the server', function(done, server, client) {
    server.eval(function() {
        Posts.find().observe({
            added: addedNewPost
        });

        function addedNewPost(post) {
            emit('post', post);
        }
    }).once('post', function(post) {
        assert.equal(post.title, 'hello title');
        done();
    });
    client.eval(function() {
        Posts.insert({title: 'hello title'});
    });
});
```

However I always get a timeout. 

```
 1) Posts using both client and the server:
     Error: timeout of 2000ms exceeded at null.<anonymous>
(/usr/local/share/npm/lib/node_modules/laika/node_modules/mocha/lib/runnable.js:165:14)
at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

The 'in the server' test passes ok. Maybe its something to do with observe()? Increasing the timeout period does not help. I'm not sure how to get some output to help narrow things down a bit.

Any ideas? 

I'd really like to use laika as it looks like it will simplify the testing workflow. Thanks.

**Comment by arunoda** [comment]
Try this and see

``` js
test('using both client and the server', function(done, server, client) {
      server.eval(function() {
          Posts.find().observe({
              added: addedNewPost
          });

          function addedNewPost(post) {
              emit('post', post);
          }
          emit('ready')
      }).once('post', function(post) {
          assert.equal(post.title, 'hello title');
          done();
      }).once('ready', function() {
        client.eval(function() {
            Posts.insert({title: 'hello title'});
        });
      });
  });
```

OR

``` js
  test('using both client and the server', function(done, server, client) {
      server.evalSync(function() {
          Posts.find().observe({
              added: addedNewPost
          });

          function addedNewPost(post) {
              emit('post', post);
          }
          emit('return');
      })

      server.once('post', function(post) {
          assert.equal(post.title, 'hello title');
          done();
      });

      client.eval(function() {
          Posts.insert({title: 'hello title'});
      });
  });
```

**Comment by Twark** [comment]
I've the same issue here. The two other solutions doesn't seem to work either for me.
I also tried on another example (user authorization), with the same results.

**Comment by arunoda** [comment]
The code you provide, works for me. Can you please tell me bit about your env.
Try updating laika too.

**Comment by Twark** [comment]
Good news : I think it's linked with the node version I'm using. The error currently occurs with node 0.10.10. I tried to switch to 0.10.4 (I'm using homebrew on os x), the tests are now working (even the original test)
It would be interesting to know if anyone also has the same issue with the same node version.

**Comment by arunoda** [comment]
hmmm. Interesting.
BTW: you got it fixed. That's the best part :)

On Sat, Jun 15, 2013 at 1:13 AM, Twark notifications@github.com wrote:

> Good news : I think it's linked with the node version I'm using. The error
> currently occurs with node 0.10.10. I tried to switch to 0.10.4 (I'm using
> homebrew on os x), the tests are now working (even the original test)
> It would be interesting to know if anyone also has the same issue with the
> same node version.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/15#issuecomment-19477577
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by hoolymama** [comment]
Yes I am using node 0.10.10 too. I tried the solutions above, and I tried in a different login and with hello-laika.
@Twark thanks for tracking it down. I'll go back to  node 0.10.4  I guess

**Comment by snize** [comment]
On node v0.10.11 (using homebrew on osx) doesn't gives timeout.

**Comment by arunoda** [comment]
There are some issues working with following node versions. upgrade to something else (prefer latest)
- 0.10.8
- 0.10.9
- 0.10.10

**Comment by pradeepmogi** [comment]
I'am getting same error, my environment details as follows 
node -v
v0.10.24
laika -v
0.3.1
