### ISSUE TITLE
Getting error during installation . 

### ISSUE THREAD

**Issue by Shekharrajak** [arunoda/laika#152]
Tried in many ways but not able to install laika. 
![laika](https://cloud.githubusercontent.com/assets/5774448/7980396/c32c97b8-0ac4-11e5-809e-bcc5bbff668e.PNG)

**Comment by arunoda** [comment]
Liaka is dead. Use Velocity.

**Comment by Shekharrajak** [comment]
Sir ,What I have to do so that I won't get this configuration pop-up .
![config twitter](https://cloud.githubusercontent.com/assets/5774448/7982927/f1c43df6-0ad8-11e5-9819-f12dea792c04.PNG)

**Comment by apendua** [comment]
@Shekharrajak You can also try [gagarin](https://github.com/anticoders/gagarin).

**Comment by apendua** [comment]
We've added windows support quite recently.

**Comment by arunoda** [comment]
Oh yeah. Of course :)

**Comment by Shekharrajak** [comment]
:+1:  
I solved that problem and learn another new way. 
Thanks a lot. @arunoda @apendua
