### ISSUE TITLE
Pool mongodb databases

### ISSUE THREAD

**Issue by arunoda** [arunoda/laika#16]
Rather than creating db for each test, try to pool databases and clean it after the use.

This may cause, tests to run faster.

**Comment by zvictor** [comment]
sounds good

**Comment by arunoda** [comment]
I've done few tests. The bottleneck is in the clients. Not in the server and mongodb. So mongodb optimisation does not helps much to run tests faster.

So this issue will be still open but not for the milestone 0.3

**Comment by arunoda** [comment]
MongoDB is not the bottleneck, it's opening the page via PhantomJS.
