### ISSUE TITLE
Hangs without notification

### ISSUE THREAD

**Issue by subhog** [arunoda/laika#17]
When I run the `laika` command on my app, it hangs on `loading phantomjs` info. I get no message error, nor any reason why things don't work.

It's not a problem with phantom - when trying in the sample app (https://github.com/arunoda/hello-laika), it goes past this steps (and hangs later).

**Comment by arunoda** [comment]
Can you please run the app first without laika?

**Comment by subhog** [comment]
I've run the app many times before.

**Comment by arunoda** [comment]
Can you please tell me your system info.

Meteor/meteorite version.
Are you running on the latest version? If not try to update.

On Wednesday, June 19, 2013, subhog wrote:

> I've run the app many times before.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/17#issuecomment-19678267
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by subhog** [comment]
I've updated node to 0.10.12, now it works. Thanks!

**Comment by arunoda** [comment]
There are some issues working with following node versions. upgrade to something else (prefer latest)
- 0.10.8
- 0.10.9
- 0.10.10

**Comment by RobertLowe** [comment]
Ran into this, it should at least check what version of meteor you have.

**Comment by arunoda** [comment]
@RobertLowe Do you still having the issue after updating the node. There is no issues with meteor versions. 
BTW you can update laika and use -d to show some debug logs

**Comment by nickserv** [comment]
I am using Node v0.10.29. I tried wiping my Mongo DB as per #115's suggestion, though it still hangs for some reason. Any other ideas for a temporary fix?

**Comment by nickserv** [comment]
Oddly enough, I am now getting this issue on Travis CI. Travis creates a brand new VM for every build that reinstalls things like Meteor and Laika, so everything Laika uses would be cleared. However, my builds still seem to still hang. [Here's an example build that errors because of a Laika hang.](https://travis-ci.org/nicolasmccurdy/rose/builds/30406870)

I'm going to try and run a bisect in a bit to see if rolling back to an old commit fixes anything.
