### ISSUE TITLE
add Meteor log/debug compatibility

### ISSUE THREAD

**Issue by zvictor** [arunoda/laika#20]
For debugging purposes, would be interesting to have a way to see what the Meteor is printing on the console during the execution of Laika.

A `--debug` option to use with _node-inspector_ would be even better.

**Comment by arunoda** [comment]
Yes. printing client and server and logs to the console will be really useful. Yes. we can enable this as an option. 

BTW: I'm wondering how we can use node-inspector with laika. What should be the final result of using node-inspector with laika.

**Comment by arunoda** [comment]
This option added in version `0.2.5` see 848f0c7f07e01dfcbca20292ed9e95726fe7850a

You can see additional logs with -d option.

```
laika -d
```
