### ISSUE TITLE
Server Test Timeout

### ISSUE THREAD

**Issue by EricTheMagician** [arunoda/laika#25]
Hi,

There was an issue previously reported on StackOverFlow:
http://stackoverflow.com/questions/17056068/meteorjs-laika-client-and-server-test-timout

I'm currently running nodejs 0.10.12 on MacOSX 10.7 and I am still experiencing the same issue.

Edit: I meant I'm on mac 10.8

**Comment by arunoda** [comment]
Okay you get a screenshot of the console? 
Also is it possible to share the test code ?

**Comment by EricTheMagician** [comment]
![screen shot 2013-06-30 at 9 57 55 pm](https://f.cloud.github.com/assets/323436/728194/cacea36a-e1f1-11e2-9489-8e09d21740a6.png)

Here you go. I attached a screenshot with the console and the code. Its really simple tests that I am trying to setup.

If make the test run on the server (ie replace client with server), the test runs.

I installed PhatomJS 1.9.1 through homebrew.

**Comment by arunoda** [comment]
Hmm, pretty weird.
I updated phantomjs and it works correctly.

Can ensure do you have laika version `0.2.2`? (`laika -v`)
If not upgrade it.

Try to clone https://github.com/arunoda/laika and run tests on the locally.
you can do with `npm test`

Lets see if it gives an error?

On Mon, Jul 1, 2013 at 7:32 AM, thejinx0r notifications@github.com wrote:

> [image: screen shot 2013-06-30 at 9 57 55 pm]https://f.cloud.github.com/assets/323436/728194/cacea36a-e1f1-11e2-9489-8e09d21740a6.png
> 
> Here you go. I attached a screenshot with the console and the code. Its
> really simple tests that I am trying to setup.
> 
> If make the test run on the server (ie replace client with server), the
> test runs.
> 
> I installed PhatomJS 1.9.1 through homebrew.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/25#issuecomment-20260108
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by EricTheMagician** [comment]
I was running the latest laika version.

When I cloned the repo and ran the test, this is the error I got.

> > laika@0.2.1 test /Users/ericyen/git/laika
> > node_modules/.bin/mocha -u tdd -R spec -t 5000 --recursive test
> 
> sh: node_modules/.bin/mocha: No such file or directory
> npm ERR! weird error 127
> npm ERR! not ok code 0

I also made sure to reinstall mocha, but I still got the same error.

**Comment by arunoda** [comment]
You've to first install dependancies with `npm install`

Then try.

On Mon, Jul 1, 2013 at 8:13 AM, thejinx0r notifications@github.com wrote:

> I was running the latest laika version.
> 
> When I cloned the repo and ran the test, this is the error I got.
> 
> laika@0.2.1 test /Users/ericyen/git/laika
> node_modules/.bin/mocha -u tdd -R spec -t 5000 --recursive test
> 
> sh: node_modules/.bin/mocha: No such file or directory
> npm ERR! weird error 127
> npm ERR! not ok code 0
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/25#issuecomment-20260931
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by EricTheMagician** [comment]
I did that,
And all the tests are passing now.

**Comment by arunoda** [comment]
Hmm. I wonder what cause the issue.

Can you try evalSync instead sync -
http://arunoda.github.io/laika/syntax-suger.html ?

On Mon, Jul 1, 2013 at 8:22 AM, thejinx0r notifications@github.com wrote:

> I did that,
> And all the tests are passing now.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/25#issuecomment-20261116
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by EricTheMagician** [comment]
I tried evalSync instead. Same error.
I wrapped the code in evalSync in a setTimeout. Same error.
I replaced client.evalSync with server.evalSync. Same error. ( replacing client with server was previously working)
I replaced server.evalSync with server.eval. it works again.

(Yes, I made sure to comment out the client/server.once call after he evalSync calls)

**Comment by EricTheMagician** [comment]
Problem partially solved.

I have some server code that loads a fair amount of data into the database. 
When I comment out that line of code, it works.

But obviously, I don't want to have to comment out my code to run the test.
So, is there any way for me, from within my code to identify if it is running the laika tests or not?

**Comment by kevinharvey** [comment]
I had the same problem with some code in a Meteor.startup() block that preloaded a bunch of data. I added an environment variable to my Laika run, checking for the environment variable in the startup script, and not running the load script if the environment variable was true.

**Command**

```
$ TEST=1 laika
```

**Code**

```
Meteor.startup(function () {
    if ( !process.env.TEST ) {
        loadData(); // or whatever
    }
});
```

The downside of course is that you have to create any data you want preloaded in the test. I'd be interested in some way to load data before a test, a la Django fixtures.

**Comment by EricTheMagician** [comment]
Perfect.
I will do that.

Since it's pretty much solved, and I'm not a heavy github user, I have a github etiquette question.
should I close this issue? or leave it opened as a feature request?

**Comment by arunoda** [comment]
Fixtures is a features we should badly needed. You can close the issue. We'll open another issue for the fixtures and continue the discussion on it.
