### ISSUE TITLE
Alternative to `once`

### ISSUE THREAD

**Issue by zvictor** [arunoda/laika#27]
I am trying to test reactivity, so it is expected to emit values more than once. How to treat this?  Are there any alternatives for the `once` method? Where is this `once` method defined?

**Comment by arunoda** [comment]
try on instead.

On Fri, Jul 5, 2013 at 11:07 PM, zVictor notifications@github.com wrote:

> I am trying to test reactivity, so it is expected to emit values more than
> once. How to treat this? Are there any alternatives for the once method?
> Where is this once method defined?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/27
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by zvictor** [comment]
Oh, for sure! I have forgotten the `on` method, but examples of it can be found [here](http://arunoda.github.io/laika/syntax-suger.html).

So, are these methods being inherited from the nodejs [EventEmitter](http://nodejs.org/api/events.html#events_emitter_on_event_listener)?

**Comment by arunoda** [comment]
Yes. Exactly.

On Fri, Jul 5, 2013 at 11:18 PM, zVictor notifications@github.com wrote:

> Oh, for sure! I have forgotten the on method, but examples of it can be
> found here http://arunoda.github.io/laika/syntax-suger.html.
> 
> So, are these methods being inherited from the nodejs EventEmitterhttp://nodejs.org/api/events.html#events_emitter_on_event_listener
> ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/27#issuecomment-20531037
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
Hope I can close this.
