### ISSUE TITLE
Javascript Function Testing

### ISSUE THREAD

**Issue by wbashir** [arunoda/laika#3]
Can i create function/Unit test with 'laika' ?  I have packages/modules written that are used by my Meteor.Methods to fetch and process data. I would like to test an entire suite of them using some sort of a match ?

**Comment by arunoda** [comment]
You can use `laika` for the functional testing. Just use `server.eval()` to run you codes on the server and get the result. If your package can be access with the meteor app, then it can be tested with laika.

See some examples: http://arunoda.github.io/laika/examples.html

did I answer your question?

**Comment by wbashir** [comment]
Yep, that answers my question. I was looking for the server.eval() method. I am looking to get started next week on testing.

Thanks
