### ISSUE TITLE
CoffeeScript support

### ISSUE THREAD

**Issue by Crenshinibon** [arunoda/laika#31]
Laika should support, that Meteor app and package code as well as Laika test code is written in CoffeeScript.

**Comment by arunoda** [comment]
Yes. This is a must to do.
For now, you can complile coffee into js before running tests.

Also patches are welcome :)

On Wed, Jul 10, 2013 at 10:02 AM, Dirk Porsche notifications@github.comwrote:

> Laika should support, that Meteor app and package code as well as Laika
> test code is written in CoffeeScript.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/31
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by Crenshinibon** [comment]
Yes, I can validate this workaround.

I will have a look at the sources. In case I find my way around easily, I will try to make 'native' CoffeeScript work. What is your preferred way this should work?

Looking at the apps packages and in case CoffeeScript is installed pick up CoffeeScript test files?
In case there are CoffeeScript test files pick them straight up?
A 'compiler' option when starting Laika (like Mocha does this)?
Something else?

Regards
Dirk

**Comment by arunoda** [comment]
I think compile option would be great. Since laika uses mocha internally, I
think this will be pretty easy.
I prefer auto detecting .cofee files and compile automatically.

See `bin/_laika` for the mocha invocation

On Wed, Jul 10, 2013 at 10:49 AM, Dirk Porsche notifications@github.comwrote:

> Yes, I can validate this workaround.
> 
> I will have a look at the sources. In case I find my way around easily, I
> will try to make 'native' CoffeeScript work. What is your preferred way
> this should work?
> 
> Looking at the apps packages and in case CoffeeScript is installed pick up
> CoffeeScript test files?
> In case there are CoffeeScript test files pick them straight up?
> A 'compiler' option when starting Laika (like Mocha does this)?
> Something else?
> 
> Regards
> Dirk
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/31#issuecomment-20722153
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
added in version `0.2.12`
see #32 for more info
