### ISSUE TITLE
[Questions] Acceptance testing + using other libraries

### ISSUE THREAD

**Issue by lacco** [arunoda/laika#37]
Hi! I just started learning Meteor this week, and I am trying to integrate laika as test framework. During this process I stumpled upon two questions:
1. I would like to do some kind of acceptance testing with asynronous actions, i.e. something like: "When user clicks button X, Y should happen". In code:

``` javascript
    test('in the server', function(done, server, client) {
      client.eval(function(){
        $("input[name=url]").val("http://github.com");
        $("button").click();
        // We have to wait until async operation is finished -> how?
        assert($("#output").text(), "This is github.com.");
        emit('done');
      });

      client.once('done', function(){
        done();
      });
    });
```

How do I solve this, do I have to use something like `setTimeout`?
1. I would like to use Sinon.js for mocking - how do I achieve this? As far as I see there is no package.json which is used by laika where I could ass Sinon as dependency.

Thx for you help!

**Comment by arunoda** [comment]
- For acceptance testing, laika is not good yet! See @xolvio 's https://github.com/xolvio/rtd
- You can try installing `sinon` globally and use. hope @zvictor can help you out.
