### ISSUE TITLE
Buffer encoding error

### ISSUE THREAD

**Issue by wbashir** [arunoda/laika#38]
I might be missing something here but does laika not work with node `v0.8.16`. I tried running and i get this odd error.

` injecting laika...
  loading phantomjs...
  loading initial app pool...

buffer.js:434
      throw new Error('Unknown encoding');
            ^
Error: Unknown encoding
    at Buffer.toString (buffer.js:434:13)
    at Object.fs.readFileSync (fs.js:236:33)
    at Object.getMeteoriteNode (/usr/local/share/npm/lib/node_modules/laika/lib/helpers.js:42:33)
    at detectConfig (/usr/local/share/npm/lib/node_modules/laika/lib/app_pool.js:83:35)
    at new AppPool (/usr/local/share/npm/lib/node_modules/laika/lib/app_pool.js:16:19)
    at module.exports.run.mochaOptions.reporter (/usr/local/share/npm/lib/node_modules/laika/bin/_laika:87:17)
    at start.queue (/usr/local/share/npm/lib/node_modules/laika/node_modules/qbox/lib/qbox.js:38:5)
    at Array.forEach (native)
    at QBox.start (/usr/local/share/npm/lib/node_modules/laika/node_modules/qbox/lib/qbox.js:37:10)
    at QBox.tick (/usr/local/share/npm/lib/node_modules/laika/node_modules/qbox/lib/qbox.js:58:10)`

**Comment by arunoda** [comment]
This is something weird. I tried locally with this node version. Works for me.

Anyway: this is the line cause the error: https://github.com/arunoda/laika/blob/master/lib/helpers.js#L42
I'm doing it correctly. Not sure about the error. Try updating node to a later version

**Comment by wbashir** [comment]
How are you running laika. Do you have mongo and meteor running then execute the laika command?

**Comment by arunoda** [comment]
mongo and laika only.

On Sun, Jul 21, 2013 at 7:06 AM, warsamebashir notifications@github.comwrote:

> How are you running laika. Do you have mongo and meteor running then
> execute the laika command?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/38#issuecomment-21303526
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by wbashir** [comment]
laika code injected and listening on: 19630

Shows up even when i am not running a separate mongo instance or laika itsefl?

**Comment by arunoda** [comment]
Laika injects some code to your project. It is a 2 files with the same
name. On *client *and *server *folder.
If laika runs okay, it will remove those files. But now it doesn't. Please
remove those files before you send them to production.

On Mon, Jul 22, 2013 at 1:35 AM, warsamebashir notifications@github.comwrote:

> laika code injected and listening on: 19630
> 
> Shows up even when i am not running a separate mongo instance or laika
> itsefl?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/38#issuecomment-21316009
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by Sivli-Embir** [comment]
I am getting this issue when my app has a .json file in it. In this case I was using meteorite 0.6.9 which is much more meteor like. By removing my smart.json and smart.lock Laika works fine. Not sure if its related to the original problem though...

**Comment by arunoda** [comment]
Hmm. Weird issue.
Let me see, if i can reproduce here

On Tuesday, August 6, 2013, Conner wrote:

> I am getting this issue when my app has a .json file in it. In this case I
> was using meteorite 0.6.9 which is much more meteor like. By removing my
> smart.json and smart.lock Laika works fine. Not sure if its related to the
> original problem though...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/38#issuecomment-22147739
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
This is fixed and published in `0.2.23`
