### ISSUE TITLE
Cannot pass functions to evaluated code via arguments.

### ISSUE THREAD

**Issue by knubie** [arunoda/laika#46]
I'm trying to pass helper functions a la

``` javascript
server.eval(function(foo) {
  foo();
}, function() { console.log('bar') } );
```

Results in: `TypeError: 'null' is not a function (evaluating 'foo()')`

Forgive me if this is a naive approach, is there some other way to create helper functions that can be used throughout multiple `tests()`'s?

**Comment by arunoda** [comment]
You can't pass functions like this. You can only pass variables that can be JSONed. Here is how you can do this.

``` js
setFoo = function() {
  foo = function () {
    console.log('does your things', arguments).
  }
  emit('return');
}

suite('Your Suite', function() {
  test('you test', function(done, server, client) {
    server.evalSync(setFoo);
    server.evalSync(function() {
      foo(10, 20);
      emit('return');
    });
    done();
  });
});
```

**Comment by knubie** [comment]
Oh, I see. This makes perfect sense, thank you :-)
