### ISSUE TITLE
What is the difference between server.once and server.on?

### ISSUE THREAD

**Issue by sbefort** [arunoda/laika#55]
In your article at sitepoint, you state the following:

"you can send some results back to test with emit() and catch it with server.once or server.on"

What's the difference?  Thanks.

http://www.sitepoint.com/test-driven-development-with-meteor/

**Comment by arunoda** [comment]
See nodejs eventemitter documentation.

On Monday, September 16, 2013, Shaun Befort wrote:

> In your article at sitepoint, you state the following:
> 
> "you can send some results back to test with emit() and catch it with
> server.once or server.on"
> 
> What's the difference? Thanks.
> 
> http://www.sitepoint.com/test-driven-development-with-meteor/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/55
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
This is the EventEmitter documentation for the reference purpose: http://nodejs.org/api/events.html
