### ISSUE TITLE
How to remove?

### ISSUE THREAD

**Issue by davidworkman9** [arunoda/laika#56]
I'm trying to figure out how to remove Laika, everytime my meteor server restarts it says "laika injected and listening on: _someport_".

I think it's causing some issues, but I can't be sure until I can get it to not run.

**Comment by arunoda** [comment]
Laika added 2 files to your project. You can remove by either running laika completely or remove them manually. Those files are
- `client/meteor-suite-client.js`
- `server/meteor-suite-server.js`

**Comment by davidworkman9** [comment]
Thanks very much.
