### ISSUE TITLE
laike with phantomjs localstorage

### ISSUE THREAD

**Issue by sacketty** [arunoda/laika#57]
I can see that phantom initialization within laika is made with a single parameter " {'load-images': false}". In case you have a webapp that uses local storage we can't add phantomjs standard parameter i.e.: "--local-storage-path=/some/path".
Does anyone has a workaround for this ?

**Comment by arunoda** [comment]
I really not understand the problem.
Laika works well with localStorage.

**Comment by sacketty** [comment]
You are right! it was my mistake. I had a simultaneous check for localstorage and geolocation. The problem did not come from localstorage but from geolocation which does not seems to be supported by phantomjs
