### ISSUE TITLE
test with iron-router

### ISSUE THREAD

**Issue by mattuuh7** [arunoda/laika#66]
In my test I confirmed `Meteor.isClient===true`, but was not able to load [iron-router](https://github.com/EventedMind/iron-router) modules. Can you please show whether this is doable with the current implementation?
Thanks,

**Comment by arunoda** [comment]
Can you please provide more information.
May be you've already got this fixed or given up.

**Comment by lalomartins** [comment]
I'm not sure what you (@mattuuh7) mean, since there's no loading modules in Meteor :smirk_cat: Do you mean the Router object is not available? It seems to be there for me.
