### ISSUE TITLE
failed to build on new OSX 10.8.5

### ISSUE THREAD

**Issue by michaelbishop** [arunoda/laika#68]
```
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Darwin 12.5.0
gyp ERR!npm http 200 https://registry.npmjs.org/glob/3.2.1
 command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/laika/node_modules/fibers
gyp ERR! node -v v0.10.20
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm http GET https://registry.npmjs.org/glob/-/glob-3.2.1.tgz
Build failed
```

Mac OSX 10.8.5, new laptop, make was missing. Xcode needs to be installed and I had to install the Command Line Tools from within Xcode: "Preferences > Downloads > Components".

There was also a build error because I had not run Xcode and accepted the license.

Might want to include on the install docs that it requires Xcode to be installed, license accepted and Command Line Tools installed. Also, Terminal needs to be reopened because the system path is added to after Command Line Tools are installed.

http://stackoverflow.com/questions/9374186/i-installed-xcode-4-on-lion-mac-os-x-10-7-3-but-the-make-command-is-still-no

Thanks for building a testing framework for Meteor!

**Comment by arunoda** [comment]
Yes. You need it. I'll update the docs.

**Comment by brandonaaskov** [comment]
For what it's worth, this turned up in my search for a solution in running [johnny-five](https://github.com/rwaldron/johnny-five) on my Arduino Uno, and when I ran `npm install johnny-five` I got the exact same gyp error stack above. Same solution! Awesome! Thank you!
