### ISSUE TITLE
--debug-brk not stopping on breakpoint

### ISSUE THREAD

**Issue by AdrienLemaire** [arunoda/laika#73]
Hi,

If I understood correctly, when adding **--debug-brk** in my `laika.opts` and adding **debugger** on one line in my tests, it should stop on that line and allow me to examine the state at that point.

But laika ignores the line and keep running.

**Comment by arunoda** [comment]
I think this is not working. 
I need to change how laika handles this bit differently. I'll do it around this week.

Frankly we need to do something [similar](https://github.com/visionmedia/mocha/blob/master/bin/mocha) done with mocha to handle this situation. 
Just passing the option to Mocha is not gonna implement this.

If you can send me a Pull Request, it would be nice.

**Comment by AdrienLemaire** [comment]
I see... Unfortunately, I only recently started to learn all those technologies, and don't think I can take care of it :) Maybe I'll go and create a new ticket in the mocha bug tracker then, thank you

**Comment by arunoda** [comment]
Ah nope. It's not a mocha issue rather laika does not implemented it well.
I'll do it the next week.

On Sun, Jan 12, 2014 at 9:04 AM, Adrien Lemaire notifications@github.comwrote:

> I see... Unfortunately, I only recently started to learn all those
> technologies, and don't think I can take care of it :) Maybe I'll go and
> create a new ticket in the mocha bug tracker then, thank you
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/73#issuecomment-32114337
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by AdrienLemaire** [comment]
oh ok :) Thank you very much for your support !
