### ISSUE TITLE
Laika not importing classes properly

### ISSUE THREAD

**Issue by AdrienLemaire** [arunoda/laika#75]
Hi,

I successfully wrote some code where meteor builds a collection transforming via a class, and printing it in the template.
But when I try to execute some basic laika tests, and the `bitcoin.coffee` file is read, it fails to  find `@BaseCrypto`, class which is found by meteor when running it.

![laika_fail](https://f.cloud.github.com/assets/260983/1865857/fa0584b6-781c-11e3-970f-cfb888056b98.png)

Any idea why meteor would find the class and not Laika ? How can I fix this issue ?

**Comment by arunoda** [comment]
I'm not why it is. Can you provide me something to reproduce it locally. Then I can test.

**Comment by AdrienLemaire** [comment]
Fastest way is:

```
$ git clone https://github.com/CoinsManager/CoinsManager.git
$ cd CoinsManager && git checkout alpha && laika -V
```

It's already very simple, but I'll setup a more basic example tomorrow if you prefer.

**Comment by arunoda** [comment]
I think I can try it tomorrow.

On Sun, Jan 12, 2014 at 8:55 AM, Adrien Lemaire notifications@github.comwrote:

> Fastest way is:
> 
> $ git clone https://github.com/CoinsManager/CoinsManager.git
> $ cd CoinsManager && laika -V
> 
> It's already very simple, but I'll setup a more basic example tomorrow if
> you prefer.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/75#issuecomment-32114218
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by AdrienLemaire** [comment]
Most simple way to test:

```
$ meteor create laika_classes_issue
$ cd laika_classes_issue && mkdir {tests,models}
```

Then add those files:
- **laika.opts**
  
  ```
  --ui bdd
  --compilers coffee:coffee-script
  ```
- **models/base_model.coffee**
  
  ```
  class @BaseModel
  ```
- **models/model.coffee**
  
  ```
  class @Model extends @BaseModel
  
  exports.Model = Model unless Meteor?
  ```
- **tests/model_spec.coffee**
  
  ```
  {BaseModel} = require "#{__dirname}/../models/base_model"
  {Model} = require "#{__dirname}/../models/model"
  
  
  describe 'BaseModel', ->
  
    it 'exists', ->
      BaseModel.should.be.ok
  
  
  describe 'Model', ->
  
    it 'exists', ->
      Model.should.be.ok
      Model.should.be.an.instanceOf BaseModel
  ```

Then run `laika`, and you should see that error:

![traceback](http://i.imgur.com/58aubCJ.png)

On the other hand, meteor has no problem with [loading the classes](https://github.com/CoinsManager/CoinsManager/blob/alpha/collections/coins.coffee) (from [CoinsManager/alpha](https://github.com/CoinsManager/CoinsManager/tree/alpha), result [here](http://alpha.coinsmanager.com/))

**Comment by AdrienLemaire** [comment]
bump on this issue

**Comment by AdrienLemaire** [comment]
Hi Arunoda, did you make any progress on that issue ? Thank you for your support !

**Comment by AdrienLemaire** [comment]
No support, switched over to RTD. I'll try again laika when it will be integrated to RTD
