### ISSUE TITLE
Request a large number of clients without typing them all out in advance?

### ISSUE THREAD

**Issue by mizzao** [arunoda/laika#76]
Hi @arunoda,

Is there way to set up a large, fixed number of laika clients without having to type out `(..., c1, c2, c3, ...)`?

**Comment by arunoda** [comment]
hmm, it is hard to do that with laika. You might need to look for some load
testing script.

On Fri, Jan 17, 2014 at 9:11 PM, Andrew Mao notifications@github.comwrote:

> Hi @arunoda https://github.com/arunoda,
> 
> Is there way to set up a large number of laika clients without having to
> type out (c1, c2, c3, ...)?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/76
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
