### ISSUE TITLE
Do not exit when there is an error

### ISSUE THREAD

**Issue by arunoda** [arunoda/laika#8]

**Comment by zvictor** [comment]
+1

**Comment by zvictor** [comment]
I am not sure if that is the matter being discussed here, but the following should be accepted:

``` js
(function(){
    server.evalSync(function() {

        throw new Error('fail');
        emit('return');

      });
}).should.throw();
```

For now it prints an `Uncaught [ Server Crashed ] Error` on the console.

**Comment by arunoda** [comment]
I hope this `should` method comes from should js libraray?
Unfortunately there is no way to install custom nodejs modules. But I have plans to work on it.

Possible solution is something like this

``` js
assert.throws(function() {
    server.evalSync(function() {

        throw new Error('fail');
        emit('return');

    });
});
```

unfortunately it is also not working. Laika can't catch exceptions like this yet occurred from the server

**Comment by arunoda** [comment]
I created a new issue for this #10

**Comment by zvictor** [comment]
Yeah, it is a `should.js` method.
I am using `should` inside of my laika tests without problems and this method is the only one that does not work.

My temporary solution is to use try/catch in the server and emit a flagged result to laika.

**Comment by arunoda** [comment]
Yes. That'll fix for now. I'll work on evalSync() error catching.
BTW: How do you use `should.js` with this. Did you install it to your
meteor project?

On Wed, Jun 12, 2013 at 2:52 AM, zVictor notifications@github.com wrote:

> Yeah, it is a should.js method.
> I am using should inside of my laika tests without problems and this
> method is the only one that does not work.
> 
> My temporary solution is to use try/catch in the server and emit a flagged
> result to laika.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/8#issuecomment-19293249
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by zvictor** [comment]
No. I have installed it globally and just required it in a _setup.js_ I added in **/test**.

setup.js:

``` js
should = require('should').should;
_ = require('underscore');
```

**Comment by arunoda** [comment]
Ah cool. That should work. :)

On Wed, Jun 12, 2013 at 3:06 AM, zVictor notifications@github.com wrote:

> No. I have installed it globally and just required it in a _setup.js_ I
> added in _/test_.
> 
> setup.js:
> 
> should = require('should').should;_ = require('underscore');
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/8#issuecomment-19294040
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
We can continue the conversation related to error catching in `.evalSycn` in #10
